### ISSUE TITLE
Not working with jupyter lab 2.0.1

### ISSUE THREAD

**Issue by fran6co** [RoboStack/jupyter-ros#55]
I'm getting this error:
```
index.js:276 Plugin 'jupyter-ros' failed to activate.
(anonymous) @ index.js:276
index.js:277 Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    at f.e.resolveRequiredService (index.js:191)
    at index.js:149
    at Array.map (<anonymous>)
    at f.e.activatePlugin (index.js:149)
    at index.js:275
    at Array.map (<anonymous>)
    at f.e.start (index.js:274)
    at o (index.out.js:1059)
```

Digging in the problem comes from base.IJupyterWidgetRegistry in  https://github.com/RoboStack/jupyter-ros/blob/master/js/lib/labplugin.js#L14 not being the same object as the object saved in the serivice map. I think it's because the deduplication step is not doing what it should, when I install with `jupyter labextension install jupyter-ros --debug` I'm getting:

```
> node /usr/local/lib/python3.6/dist-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
|yarn run v1.21.1
$ /usr/local/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Not sure how to fix this one

**Comment by fran6co** [comment]
I think I figured it out, but the man the errors should be a bit easier to read. I think the problem is that this extension depends on @jupyter-widgets/base < 2.0 and what gets installed is 3.0.0 instead.

**Comment by ldecicco** [comment]
Hi, I am hitting this bug too. @fran6co  did you fix this?

**Comment by ldecicco** [comment]
I confirm that everything works as expected in jupyter notebooks but not in jupyter lab v. 2.0.1.

**Comment by fran6co** [comment]
@ldecicco no, I did not fix it, I just switched to jupyter notebook instead and it works there

**Comment by Tobias-Fischer** [comment]
This should work with the latest release.
